import { StyleSheet } from 'react-native';
import { colors } from '../../../utils/colors';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 25,
    paddingTop: 40,
    paddingBottom: 40,
    backgroundColor: colors.backgroundPrimary,
    justifyContent: 'center',
  },
  avoidContainer: {
    flex: 1,
    backgroundColor: colors.backgroundPrimary,
  },
  headerText: {
    fontSize: 21,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 22,
    textAlign: 'center',
    lineHeight: 27,
  },
  topLogo: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignSelf: 'center',
    marginBottom: 10,
  },
  input: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    height: 55,
    borderRadius: 12,
    paddingHorizontal: 15,
    fontSize: 16,
    color: colors.textPrimary,
    marginTop: 15,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 12,
    height: 55,
    marginTop: 15,
    overflow: 'hidden',
  },
  inputError: {
    borderColor: colors.danger,
    backgroundColor: colors.inputBg,
  },
  iconButton: {
    height: '100%',
    paddingHorizontal: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: colors.danger,
    fontSize: 12,
    marginTop: 5,
    marginLeft: 5,
    fontWeight: '600',
  },
  btn: {
    backgroundColor: colors.primary,
    height: 55,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  googleBtn: {
    marginTop: 0,
    backgroundColor: colors.surfaceSecondary,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 999,
    elevation: 0,
    shadowOpacity: 0,
  },
  googleBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  googleLogo: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  googleBtnText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  btnText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  orText: {
    marginTop: 14,
    marginBottom: 14,
    textAlign: 'center',
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  otpInfoText: {
    marginTop: 10,
    textAlign: 'center',
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  resendLink: {
    marginTop: 10,
    alignSelf: 'center',
  },
  resendText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  new: {
    marginTop: 20,
  },
  text1: {
    color: colors.primary,
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 14,
  },
  homeLink: {
    marginTop: 10,
  },
  homeText: {
    color: colors.textSecondary,
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 14,
  },
  text: {
    color: colors.textSecondary,
    textAlign: 'center',
    fontSize: 14,
  },
});
