import { StyleSheet } from 'react-native';
import { colors } from '../../../utils/colors';

export const styles = StyleSheet.create({
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  rightIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconBtn: {
    padding: 8,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSearchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingLeft: 12,
    paddingRight: 8,
    height: 44,
    marginRight: 12,
  },
  headerSearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    paddingVertical: 0,
  },
  headerSearchCloseBtn: {
    padding: 4,
    marginLeft: 6,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 8,
  },
  logo: {
    width: 32,
    height: 32,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: colors.textPrimary,
    backgroundColor: colors.surfaceSecondary,
    resizeMode: 'cover',
    overflow: 'hidden',
  },
  Title: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
    marginLeft: 15,
  },
  cartWrapper: {
    padding: 5,
    marginLeft: 30,
    position: 'relative',
  },
  cartLogo: {
    height: 35,
    width: 35,
    resizeMode: 'contain',
    tintColor: colors.textPrimary,
  },
  badge: {
    position: 'absolute',
    right: -2,
    top: -2,
    backgroundColor: colors.danger,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.textPrimary,
  },
  badgeText: {
    color: colors.textPrimary,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 14,
  },
  shutterBtn: {},
  shutterText: {},
});
