import { StyleSheet } from 'react-native';
import { colors } from '../../utils/colors';

export const drawerContentStyles = StyleSheet.create({
  drawerContent: {
    backgroundColor: colors.backgroundSecondary,
    flex: 1,
  },
  profileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 16,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.surfacePrimary,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  profileTextContainer: {
    marginLeft: 10,
    flex: 1,
  },
  profileName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  profileEmail: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  drawerItem: {
    backgroundColor: colors.surfacePrimary,
    marginVertical: 6,
    marginHorizontal: 12,
    borderRadius: 12,
    paddingVertical: 4,
  },
  drawerLabel: {
    fontSize: 15,
    color: colors.textPrimary,
    fontWeight: '600',
    marginLeft: 10,
  },
  drawerActive: {
    backgroundColor: colors.primary + '22',
  },
  logoutItem: {
    backgroundColor: '#FFE4E6',
    borderWidth: 1.2,
    borderColor: '#FCA5A5',
    marginTop: 'auto',
    marginBottom: 22,
    marginHorizontal: 16,
    borderRadius: 12,
    minHeight: 48,
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 6,
    elevation: 3,
  },
  logoutLabel: {
    color: '#B91C1C',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
    marginLeft: 0,
    textAlign: 'center',
  },
  loginItem: {
    backgroundColor: '#DBEAFE',
    borderWidth: 1.2,
    borderColor: '#93C5FD',
    marginTop: 'auto',
    marginBottom: 22,
    marginHorizontal: 16,
    borderRadius: 12,
    minHeight: 48,
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 6,
    elevation: 3,
  },
  loginLabel: {
    color: '#1D4ED8',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
    marginLeft: 0,
    textAlign: 'center',
  },
  iconWrapper: {
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    top: -5,
    right: -8,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.danger,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
  },
  badgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '700',
  },
});
