import { StyleSheet } from 'react-native';
import { colors } from '../../../utils/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundPrimary,
    paddingHorizontal: 10,
  },
  columnWrapper: {
    justifyContent: 'space-between',
  },
  card: {
    backgroundColor: colors.surfacePrimary,
    width: '48%',
    marginBottom: 16,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
  },
  Imgcontainer: {
    backgroundColor: colors.surfaceSecondary,
    height: 150,
    width: '100%',
    padding: 10,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  contentBox: {
    padding: 12,
  },
  category: {
    fontSize: 9,
    color: colors.primary,
    textTransform: 'uppercase',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  name: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 4,
  },
  desc: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 4,
    lineHeight: 16,
    height: 32,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
  price: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.success,
  },

  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 100,
  },
  empty: {
    textAlign: 'center',
    marginTop: 50,
    fontSize: 16,
    color: colors.textMuted,
    fontWeight: '600',
  },
  welcome: {
    position: 'absolute',
    top: 80,
    right: 20,
    zIndex: 1000,
    backgroundColor: colors.primary,
    padding: 12,
    borderRadius: 8,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    maxWidth: '70%',
  },
  welcomeText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  welcomeText1: {
    padding: 4,
  },
  chatIconContainer: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: colors.primary,
    borderRadius: 20,
    padding: 6,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  chatIcon: {
    color: colors.textPrimary,
    fontSize: 18,
  },
  searchFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 6,
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surfaceSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchBox: {
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 8,
  },
  searchInput: {
    color: colors.textPrimary,
    padding: 0,
    fontSize: 14,
  },
  filterAnchor: {
    position: 'relative',
    minHeight: 1,
    zIndex: 50,
    overflow: 'visible',
  },
  filterBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
    backgroundColor: 'rgba(0, 0, 0, 0.12)',
  },
  filterModalContainer: {
    flex: 1,
    paddingHorizontal: 10,
    paddingTop: 150,
    alignItems: 'flex-end',
  },
  filterPanel: {
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    width: '72%',
    alignSelf: 'flex-end',
    minHeight: 0,
    elevation: 8,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  sliderWrap: {
    marginBottom: 8,
  },
  filterTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  sliderValueText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  slider: {
    width: '100%',
    height: 40,
  },
  priceBar: {
    height: 10,
    backgroundColor: colors.border,
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 6,
    marginBottom: 10,
  },
  priceFill: {
    height: '100%',
    backgroundColor: colors.primary,
  },
  priceStepsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  priceStep: {
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.surfacePrimary,
  },
  priceStepActive: {
    borderColor: colors.primary,
    backgroundColor: colors.surfaceSecondary,
  },
  priceStepText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  priceStepTextActive: {
    color: colors.primary,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 8,
  },
  filterInput: {
    flex: 1,
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: colors.textPrimary,
  },
  filterActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 10,
  },
  filterBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyBtn: {
    backgroundColor: colors.primary,
  },
  resetBtn: {
    backgroundColor: colors.surfacePrimary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  filterBtnText: {
    color: colors.textPrimary,
    fontWeight: '700',
    fontSize: 13,
  },
  picker: {
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    height: 54,
    width: '100%',
    justifyContent: 'center',
    paddingVertical: 0,
    color: colors.textPrimary,
  },
  skeletonImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
    backgroundColor: colors.surfacePrimary,
  },
  skeletonCategory: {
    width: 70,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.surfaceSecondary,
    marginBottom: 8,
  },
  skeletonTitle: {
    width: '85%',
    height: 14,
    borderRadius: 6,
    backgroundColor: colors.surfaceSecondary,
    marginBottom: 10,
  },
  skeletonLine: {
    width: '100%',
    height: 10,
    borderRadius: 6,
    backgroundColor: colors.surfaceSecondary,
    marginBottom: 6,
  },
  skeletonLineShort: {
    width: '70%',
    height: 10,
    borderRadius: 6,
    backgroundColor: colors.surfaceSecondary,
    marginBottom: 10,
  },
  skeletonPrice: {
    width: 80,
    height: 18,
    borderRadius: 8,
    backgroundColor: colors.surfaceSecondary,
  },
});
