import { StyleSheet } from 'react-native';
import { colors } from '../../../utils/colors';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.backgroundPrimary,
    paddingHorizontal: 25,
    paddingTop: 40,
    paddingBottom: 40,
    justifyContent: 'center',
  },
  avoidContainer: {
    flex: 1,
    backgroundColor: colors.backgroundPrimary,
  },
  headerText: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 30,
    textAlign: 'center',
  },
  input: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    height: 55,
    borderRadius: 12,
    paddingHorizontal: 15,
    fontSize: 16,
    color: colors.textPrimary,
    marginTop: 15,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 12,
    height: 55,
    marginTop: 15,
    overflow: 'hidden',
  },
  passwordInput: {
    flex: 1,
    height: '100%',
    paddingHorizontal: 15,
    fontSize: 16,
    color: colors.textPrimary,
  },
  iconButton: {
    height: '100%',
    paddingHorizontal: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputError: {
    borderColor: colors.danger,
    backgroundColor: colors.inputBg,
  },
  inputSuccess: {
    borderColor: colors.success,
    backgroundColor: colors.successBg,
  },

  errorText: {
    color: colors.danger,
    fontSize: 12,
    marginTop: 5,
    marginLeft: 5,
    fontWeight: '600',
  },
  btn: {
    backgroundColor: colors.primary,
    height: 55,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  btnText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  text: {
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 20,
    fontSize: 14,
  },
  text1: {
    color: colors.primary,
    textAlign: 'center',
    marginTop: 15,
    fontWeight: 'bold',
    fontSize: 14,
  },
  new1: {
    marginTop: 10,
  },
  criteriaText: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textSecondary,
    marginLeft: 5,
    marginTop: 5,
  },
  new: {
    marginTop: 20,
  },
  Pcontainer: {
    marginTop: 10,
    marginLeft: 5,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  Ptext: {
    width: '50%',
    fontSize: 12,
    fontWeight: '500',
    color: colors.textSecondary,
  },
});
